# ============================================================================
# Docker Compose Configuration
# Cloud Security AI - Oracle Hackathon 2025
# ============================================================================
# Quick start: docker-compose up -d
# View logs: docker-compose logs -f
# Stop: docker-compose down
# ============================================================================

version: '3.8'

services:
  # ============================================================================
  # Backend Service (FastAPI)
  # ============================================================================
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: cloud-security-backend
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - HOST=0.0.0.0
      - ALLOWED_ORIGINS=http://localhost:3000,http://localhost:5173,http://localhost
      - ENVIRONMENT=production
    volumes:
      # Mount data directory for persistent storage
      - ./backend/data:/app/data
      # Mount ML models directory
      - ./backend/app/ml_models:/app/app/ml_models
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # ============================================================================
  # Frontend Service (React + Vite + Nginx)
  # ============================================================================
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: cloud-security-frontend
    ports:
      - "80:80"
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

# ============================================================================
# Networks
# ============================================================================
networks:
  app-network:
    driver: bridge
    name: cloud-security-network

# ============================================================================
# Volumes (optional - for future use)
# ============================================================================
volumes:
  backend-data:
    name: cloud-security-backend-data
